### ISSUE TITLE
Question: Adding a non headless service

### ISSUE THREAD

**Issue by smenon78** [IBM/Scalable-Cassandra-deployment-on-Kubernetes#7]
I need to add a non-headless service. I tried to change the current 
 	cassandra-service.yaml and remove the line clusterIP: None, then pods are crashing
so I had to add another service. Is this the only option?

**Comment by AnthonyAmanse** [comment]
@smenon78 That's the only option if you want to have a normal service. The headless service is there so that we can get the IP of our Cassandra seed. By having a [headless service](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/), we can get the set of IP of our Pods on the Cassandra service. In the sample, we are only using the first pod's IP as the Cassandra seed.

**Comment by mlangbehn** [comment]
Closing, since the question has been answered.
